queue_rules:
  - name: dependabot-create-nestjs-middleware-module
    queue_conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - -check-failure~=build-lint-test
      - check-success~=build-lint-test
      - check-success=security/snyk (iamolegga)
    merge_conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - -check-failure~=build-lint-test
      - check-success~=build-lint-test
      - check-success=security/snyk (iamolegga)
    merge_method: rebase

pull_request_rules:
  - name: merge pull requests from dependabot if CI passes
    conditions: []
    actions:
      queue:
