language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '12'
deploy:
  skip_cleanup: true
  on:
    repo: iamolegga/create-nestjs-middleware-module
    branch: master
  provider: npm
  email: iamolegga@gmail.com
  api_key:
    secure: WDlGcYTWU9THAgP6oSo6lCgTX0bdfgWHM6RGpBxHSIF7AkydCrsWmI0gvUCQqxXK03DS99BgWc+4LvWJ2KD6z2h2CETv4dLL6PWY9KHP8NrD+4WFI6dKe/epqAay6HLLBw5rD0hKcUxah0argA3M+DFZA6tyk+M6r80OsJC31/OzLDUd0DxJH6bUMl6rO5WAxzbZ242a9gRiniXEAekCundIjCYHBbSGIHknrJIhGxIA6hL45/ZYHIJ5hcL1cTz7ZkwAQ+oyS96Sdyy0yLgmlCJpdQe+klTdp/3WAo50FsTgesQL7ZOmBtPGMTmO4g7rDxmr9fMjIhP8LZhkmqLNu9+A8kFtIqNi+2BU6uS0h9NYrWVsbmQG34oTL9NsNtQ05fS+eSLtOx7I9lbcAYdUD2R5VjG3DCpRcv85MXj+Q2Mf4T7pXp/awog+YKBVO8xQTio0cv2fPu3uuiNjSm/yQEFzicKF76H6Zfq2CP8RiRLz3kcPuBCUrHH5dZ4YKfPrPhZeYZAU7vo52DZEa4mm5j0ZYSUKxYjFywxvFwFcfUCHYBd8hmNfK/Ww9Nu5V3m5N5hL42+TUG81HbFfVrwRkWxhPdY8Ot6m61R3frnKHwwuuRUFxj9bPJl3mKPTkn/o9kE7miUfYDP+7KxcKC2nkxm81TOBWYTZc+SVZxM/mDE=
script:
  - npm run build
  - npm run test
after_deploy:
  - npm run report
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
