name: ✨ Feature request
description: Suggest an idea for this project.
labels: enhancement
title: "[FEATURE REQUEST] "
assignees: iamolegga
body:
  - type: markdown
    attributes:
      value: |
        :warning: Please make sure you are using the latest version of this package!

        ---

  - type: input
    validations:
      required: true
    attributes:
      label: Package version
      description: Which version of `create-nestjs-middleware-module` are you using?
      placeholder: 0.2.1

  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search [here](./issues?q=is%3Aissue+label%3Abug) to see if an issue already exists for the bug you encountered
      options:
      - label: I have searched the existing issues
        required: true

  - type: markdown
    attributes:
      value: ---

  - type: textarea
    validations:
      required: true
    attributes:
      label: Is your feature request related to a problem? Please describe
      description: A clear and concise description of what the problem is
      placeholder: I'm always frustrated when ...

  - type: textarea
    validations:
      required: true
    attributes:
      label: The solution you'd like
      description: A clear and concise description of what you want to happen

  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered

  - type: textarea
    attributes:
      label: Additional context
      description: |
        Anything else relevant? eg: Logs, OS version, IDE, package manager, Node.js version, etc.
        **Tip:** You can attach images, recordings or log files by clicking this area to highlight it and then dragging files in
